#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectivityManager.Resource", IsApplication=true)]

namespace ConnectivityManager
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.3.99.16")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int gms_fair_dr = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int gms_good_dr = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int gms_none_dr = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int gms_poor_dr = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int signal = 2130771973;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int BluetoothListView = 2130837504;
			
			// aapt resource value: 0x7F020002
			public const int btnBluetooth = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnCancel = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnDial = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnGetSignalStrength = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int btnMobileData = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnNFC = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int btnOK = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int btnSettings = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int btnToggleBluetooth = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int btnToggleWiFi = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int btnWiFi = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int editText = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int imageViewMN = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int linearLayout1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int textPassword = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int textSSID1 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textViewMN = 2130837522;
			
			// aapt resource value: 0x7F020001
			public const int WiFiListView = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Bluetooth = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int NetworkSignal = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int NFC = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int PwdDialogue = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int WiFi = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
